### ISSUE TITLE
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[8,6,320,320] 

### ISSUE THREAD

**Issue by Tian14267** [li10141110/PSENet-tf2#2]
你好，你的代码是不是不能进行batch训练？当我设置batch>1的时候，就会出现下面的问题：

2020-07-08 15:13:18.850245: I tensorflow/core/common_runtime/bfc_allocator.cc:1004] total_region_allocated_bytes_: 2646605824 memory_limit_: 2646605824 available bytes: 0 curr_region_allocation_bytes_: 5293211648
2020-07-08 15:13:18.850250: I tensorflow/core/common_runtime/bfc_allocator.cc:1010] Stats: 
Limit:                  2646605824
InUse:                  2581644032
MaxInUse:               2640246784
NumAllocs:                    5164
MaxAllocSize:            639631360

2020-07-08 15:13:18.850282: W tensorflow/core/common_runtime/bfc_allocator.cc:439] ****************************************************************************************************
2020-07-08 15:13:18.850302: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at strided_slice_op.cc:248 : Resource exhausted: OOM when allocating tensor with shape[8,6,320,320] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "/home/fffan/fffan_files/Detection/tensorflow_pse/PSENet-tf2-li10141110/train_id41k.py", line 357, in <module>
    main(args)
  File "/home/fffan/fffan_files/Detection/tensorflow_pse/PSENet-tf2-li10141110/train_id41k.py", line 292, in main
    optimizer, epoch)
  File "/home/fffan/fffan_files/Detection/tensorflow_pse/PSENet-tf2-li10141110/train_id41k.py", line 176, in train
    grads = tape.gradient(loss, model.trainable_weights)
  File "/home/fffan/.local/lib/python3.7/site-packages/tensorflow/python/eager/backprop.py", line 1048, in gradient
    unconnected_gradients=unconnected_gradients)
  File "/home/fffan/.local/lib/python3.7/site-packages/tensorflow/python/eager/imperative_grad.py", line 77, in imperative_grad
    compat.as_str(unconnected_gradients.value))
  File "/home/fffan/.local/lib/python3.7/site-packages/tensorflow/python/eager/backprop.py", line 157, in _gradient_function
    return grad_fn(mock_op, *out_grads)
  File "/home/fffan/.local/lib/python3.7/site-packages/tensorflow/python/ops/array_grad.py", line 295, in _StridedSliceGrad
    shrink_axis_mask=op.get_attr("shrink_axis_mask")), None, None, None
  File "/home/fffan/.local/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 10351, in strided_slice_grad
    _ops.raise_from_not_ok_status(e, name)
  File "/home/fffan/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6653, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[8,6,320,320] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:StridedSliceGrad]

请问这是什么情况？

**Comment by li10141110** [comment]
可以batch训练的，（之前OOM是显存不够了）现在没有问题了吧

**Comment by Doge2408** [comment]
你好，请问解决了吗我也有相同的问题，是哪里有问题呢？
